### ISSUE TITLE
The HUDs are too close to the screen's edges

### ISSUE THREAD

**Issue by dmndrz** [AlexPerathoner/SlimHUD#1]
Hi.
Wherever I chose to put the HUDs, it seems they are a little too close to the edges (see screenshot). The worst is on the top, it's almost completely hidden by the menubar.

<img width="410" alt="Capture d’écran 2020-03-23 à 16 20 46" src="https://user-images.githubusercontent.com/18632343/77332830-d9495980-6d22-11ea-87b9-e58fb41beaec.png">

**Comment by AlexPerathoner** [comment]
Hi.
Does this also happen when you set the bar on the right and left side of the screen?

**Comment by dmndrz** [comment]
No, on the left and right sides it doesn't happen.
I guess it's the same marging for all 4 sides, but at the top there is the menubar so it's partially hidden. It could be solved by automatically hiding the menubar, but it's not what I (and other people I guess) prefer. That's the same for the bottom, if you don't automatically hide the dock, the HUDs would be hidden by it.

**Comment by AlexPerathoner** [comment]
Ok.. and on the bottom I think it's caused by the dock... working with both hidden wasn't good for testing 😅
I am already working on an update, in a couple of hours I should be able to release it.

**Comment by dmndrz** [comment]
Haha, yes! We're all used to have our own different workspaces. ☺️
Other than that, it works very well, it's smooth and feels like iOS.

**Comment by AlexPerathoner** [comment]
So I have solved half of that issue... now the Bar should be at the right distance on every edge, regardless of the system menu bar, the dock (and eventually which edge the dock is set to appear).

Unfortunately also when using a fullscreen app the bar appears at that same "right" distance. See screenshot:

![Schermata 2020-03-23 alle 22 34 17](https://user-images.githubusercontent.com/31958579/77365477-7d002d00-6d56-11ea-9ddb-9e25b0944965.png)

Still working on that.

**Comment by AlexPerathoner** [comment]
I have just released a new version which should fix this issue. Please confirm me if it does.

**Comment by dmndrz** [comment]
I confirm you that it's fixed! Good job 😉

**Comment by omarsonmarz** [comment]
for me, the bars are still hidden under the menu bar... here's a gif (i have the latest version: 1.3.7)
![untitled](https://user-images.githubusercontent.com/74555681/99277785-3935c880-27fc-11eb-9fdc-908921511a15.gif)

**Comment by AlexPerathoner** [comment]
> for me, the bars are still hidden under the menu bar... here's a gif (i have the latest version: 1.3.7)
> 
> ![untitled](https://user-images.githubusercontent.com/74555681/99277785-3935c880-27fc-11eb-9fdc-908921511a15.gif)
> 
> 
> 
> 

May I ask you what that screen's resolution is?

**Comment by omarsonmarz** [comment]
Color LCD: 1280 x 800
2nd Display: 1600 x 1200
(this is on the primary color lcd display btw)

**Comment by omarsonmarz** [comment]
preferences shows what i think it should be, but when i restart the app, this happens
![Untitled2](https://user-images.githubusercontent.com/74555681/99280954-f544c280-27ff-11eb-9e1d-69635a56d2c9.gif)

**Comment by AlexPerathoner** [comment]
You confirm me this issue is always present, even when the app has been running for a while?

**Comment by omarsonmarz** [comment]
> You confirm me this issue is always present, even when the app has been running for a while?
sorry for the late reply

yes, that is what happens

**Comment by AlexPerathoner** [comment]
I think I finally understood what's going on.
SlimHUD gets the main screen's dimensions. It then calculates accordingly the offset the bars should have from the screen border. Finally, it shows the bar, but on the other screen.
Please tell me if this sounds reasonable.

Try to set the same resolution for both screens and tell me the issue is still present.

**Comment by omarsonmarz** [comment]
> I think I finally understood what's going on.
> SlimHUD gets the main screen's dimensions. It then calculates accordingly the offset the bars should have from the screen border. Finally, it shows the bar, but on the other screen.
> Please tell me if this sounds reasonable.
> 
> Try to set the same resolution for both screens and tell me the issue is still present.

That makes sense. I set the same resolution and it works now, thank you!

**Comment by AlexPerathoner** [comment]
> > I think I finally understood what's going on.
> > SlimHUD gets the main screen's dimensions. It then calculates accordingly the offset the bars should have from the screen border. Finally, it shows the bar, but on the other screen.
> > Please tell me if this sounds reasonable.
> > Try to set the same resolution for both screens and tell me the issue is still present.
> 
> That makes sense. I set the same resolution and it works now, thank you!

That's not a solution xD
However, if I now know what the problem is I can start working on it. In the next days I'll release an update.
