### ISSUE TITLE
Hide menu bar icon

### ISSUE THREAD

**Issue by AlexPerathoner** [AlexPerathoner/SlimHUD#106]
### Discussed in https://github.com/AlexPerathoner/SlimHUD/discussions/105

<div type='discussions-op-text'>

<sup>Originally posted by **systracer** January 16, 2023</sup>
Please add ability to hide icon in menu bar.</div>

**Comment by kaydenanderson** [comment]
from #113 - new intended behavior is to "re-open" SlimHUD to access preferences window, now that menu bar icon is disabled completely?

**Comment by AlexPerathoner** [comment]
Hey @kaydenanderson perhaps that one message got lost too and you didn't see, but what do you think of using some more direct messaging platform? Do you know discord?

**Comment by kaydenanderson** [comment]
@AlexPerathoner i do! what’s your tag?

**Comment by AlexPerathoner** [comment]
Pera#5807

**Comment by kaydenanderson** [comment]
@AlexPerathoner sent!
