### ISSUE TITLE
Double shadow

### ISSUE THREAD

**Issue by AlexPerathoner** [AlexPerathoner/SlimHUD#109]
> @AlexPerathoner thanks for the answer. I think I didn't explain it well when I talk about shadows. See the attached image, the shadow of the "current volume" (01), is overlapping the background of the "total volume", (02), thus creating a very dark shadow due to the fact that there are two shadows, (from 01 and 02), one on top of the other. See if the image makes it clearer what I'm trying to say, please. Oh yes, sorry, I didn't know if I needed to open a new thread for this, so if needed, you can move this thread to a new one, please. Thanks again, and greetings from Rio de Janeiro, Brazil.
![CleanShot 2023-01-21 at 4 39 21](https://user-images.githubusercontent.com/123224781/213884803-879c72a2-1d1c-4972-ab33-76b209bc88c9.png)

_Originally posted by @prcmelo in https://github.com/AlexPerathoner/SlimHUD/issues/70#issuecomment-1399321622_

**Comment by AlexPerathoner** [comment]
@prcmelo I've looked a bit into this and it's actually "expected behaviour", as the background's opacity isn't the same as the one of the foreground.
However, this is expected behaviour for Apple's shadows. In this situation it definitely looks weird tho, so I'll see if I can change it

**Comment by prcmelo** [comment]
@AlexPerathoner yes, really weird from Apple, I hope you can find a way to change it. I'll be keeping a looking ate the future releases because I really like SlimHUD. Thank you!!!

**Comment by AlexPerathoner** [comment]
Using a custom made shadow (NSView with black background behind the hud) could solve this. I don't think it should impact performance.
It would then become easy to solve this, too: #17
