### ISSUE TITLE
v1.3.2 doesn't launch at login

### ISSUE THREAD

**Issue by dmndrz** [AlexPerathoner/SlimHUD#11]
Previous bug is partially solved in this version: the settings are saved after a relaunch, except for the "launch at login" one. :)

**Comment by AlexPerathoner** [comment]
[SlimHUD-v1.3.3.zip](https://github.com/AlexPerathoner/SlimHUD/files/4682554/SlimHUD-v1.3.3.zip)
This should work, please tell me if not.

**Comment by dmndrz** [comment]
Works perfectly. 👌🏼
Thanks!
