### ISSUE TITLE
No menubar icon - 1.5.0b

### ISSUE THREAD

**Issue by nkean** [AlexPerathoner/SlimHUD#113]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Updated SlimHUD to the latest version (if applicable)

### Describe the bug

After updating to the newest 1.5.0b beta release, the menubar icon has disappeared and I am unable to access settings for the app.

### Steps to reproduce

Download the newest beta release and overwrite previous version under "Applications"

### Expected behavior

The app should show the menubar icon by default (if the app now includes a setting to hide it)

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.6.2
- Mac model: 2015 MacBook Pro 13-inch (12,1)
- Monitor(s): 2 (Asus VN248)
- Apple Silicon/M1 (yes or no): no
```

**Comment by AlexPerathoner** [comment]
The menu bar icon has been removed entirely, so the app is completely in the background.
You can access the settings my starting the app "again" (double clicking on it while it's already running). I'm planning to create a welcome screen that explains this before the release - I can definitely see it being confusing.

**Comment by nkean** [comment]
Ah, that would explain it.  Attempting to access the settings menu with the above method causes it to crash on my system.

**Comment by AlexPerathoner** [comment]
Yes please, you can upload it here or if you don't feel comfortable publishing online you can also send it to me at alex.perathoner@gmail.com

**Comment by nkean** [comment]
Don't believe there's any identifying info in the logs.  For reference, these logs are from a fresh install (removed app and all config files before reinstalling)

[SlimHUD-2023-01-31-163853.ips.zip](https://github.com/AlexPerathoner/SlimHUD/files/10551913/SlimHUD-2023-01-31-163853.ips.zip)

**Comment by pirasee** [comment]
I think you should add an option for a menubar icon (hide/unhide).

**Comment by AlexPerathoner** [comment]
@nkean could you please check if the latest beta still has this problem? (regarding the opening of the settings window - an option for a menubar icon hasn't been added yet)

**Comment by nkean** [comment]
@AlexPerathoner   Newest beta update is working as intended!  No errors in console and "launching" settings from the app icon is now functioning on my install.
