### ISSUE TITLE
Top edge option doesn't work with hidden menubar

### ISSUE THREAD

**Issue by nkean** [AlexPerathoner/SlimHUD#123]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Updated SlimHUD to the latest version (if applicable)

### Describe the bug

When using the macOS setting "Automatically hide and show the menu bar on desktop", the top edge option for SlimHUD doesn't work as expected.  It appears the replacement HUD is displayed off the screen as the left, right, and bottom options all appear as expected.

### Steps to reproduce

1. Under Preferences > Dock & Menu Bar enable the option "Automatically hide and show the menu bar on desktop"
2. Configure SlimHUD to display the replacement HUD at the top edge of the display.
3. Adjust volume, screen brightness, or keyboard backlight and note the lack of on screen display

### Expected behavior

When the mentioned macOS preference setting is enabled, SlimHUD should compensate for the newly adjusted screen real estate so the replacement HUD appears on the top edge of the screen.

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.6.3
- Mac model: Early 2015 Retina MacBook Pro
- Monitor(s): 2 x Asus VN248 (External)
- Apple Silicon/M1 (yes or no): no
```

**Comment by AlexPerathoner** [comment]
Does this happen with the latest beta?

**Comment by nkean** [comment]
Looks like I didn't have the most recent beta version.  Problem doesn't appear with most recent version!
