### ISSUE TITLE
Bar background option

### ISSUE THREAD

**Issue by carsuki** [AlexPerathoner/SlimHUD#124]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

In my experience, SlimHUD has been a great replacement for cleanHUD that doesn't require any messing with SIP (especially annoying on Ventura), but visibility of the bar can be a bit tough when it's on the top of the screen. It's most noticeable with the unfilled portions of the bar in this screenshot—nearly impossible to see at a glance.

<img width="455" alt="Screenshot 2023-03-18 at 4 56 45 PM" src="https://user-images.githubusercontent.com/35876384/226146129-1c6fd52f-6c60-49cd-8c34-203b69e5e84c.png">

### Describe the solution you'd like

An option for a background behind the bar like the "Mac style" in cleanHUD would be very useful to alleviate problems with visibility. Something like this—maybe with an option for colour if not just light/dark switching—is really all that's necessary in my eyes and would be a much appreciated addition.

<img width="254" alt="Screenshot 2023-03-18 at 4 59 56 PM" src="https://user-images.githubusercontent.com/35876384/226146244-c8134620-5cc5-4ab3-bde2-b12fe60f7769.png">

### Describe alternatives you've considered

cleanHUD is the obvious choice for an alternative, but MacForge of course requires disabling SIP among other things. In Ventura disabling SIP mandates Permissive Security mode be on, which in turn disallows any Catalyst apps to open and just isn't ideal in general, especially when a solution like SlimHUD already exists.

**Comment by AlexPerathoner** [comment]
Hi @carsuki , I released a beta version which you can download in `About > Join the Beta`. Could you please try it out?

To have a similar effect to the background in your screen you can use the following settings in the `design tab -> shadow -> custom..`:
![image](https://user-images.githubusercontent.com/31958579/227390991-585a2bc4-124d-40f1-83a8-9c8a81b568da.png)

**Comment by carsuki** [comment]
Thanks for such a quick update @AlexPerathoner, works perfectly with the settings you provided. Closing the issue if you don't mind.
<img width="318" alt="Screenshot 2023-03-23 at 8 46 50 PM" src="https://user-images.githubusercontent.com/35876384/227419645-dd43c207-84d9-44a9-b2d3-e815eae1ff80.png">
