### ISSUE TITLE
auto quit silently sometime

### ISSUE THREAD

**Issue by loricheung** [AlexPerathoner/SlimHUD#13]
below is crash log
 
<details>
<summary>crash log</summary>
Process:               SlimHUD [1568]
Path:                  /Applications/SlimHUD.app/Contents/MacOS/SlimHUD
Identifier:            SlimHUD
Version:               1.3.3 (1.3.3)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           SlimHUD [1568]
User ID:               501

Date/Time:             2020-06-03 01:48:58.380 +0800
OS Version:            Mac OS X 10.15.5 (19F101)
Report Version:        12
Bridge OS Version:     4.5 (17P5300)
Anonymous UUID:        56099045-4192-4FE7-E51E-618BD81CB0F7

Sleep/Wake UUID:       3D1201FF-B0D2-4C98-893F-70D78DCE9FB6

Time Awake Since Boot: 52000 seconds
Time Since Wake:       14000 seconds

System Integrity Protection: enabled

Crashed Thread:        3  com.apple.NSEventThread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [1568]

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff6b9b0dfa mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff6b9b1170 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff3186af85 __CFRunLoopServiceMachPort + 247
3   com.apple.CoreFoundation      	0x00007fff31869a52 __CFRunLoopRun + 1319
4   com.apple.CoreFoundation      	0x00007fff31868ece CFRunLoopRunSpecific + 462
5   com.apple.HIToolbox           	0x00007fff30497abd RunCurrentEventLoopInMode + 292
6   com.apple.HIToolbox           	0x00007fff304977d5 ReceiveNextEventCommon + 584
7   com.apple.HIToolbox           	0x00007fff30497579 _BlockUntilNextEventMatchingListInModeWithFilter + 64
8   com.apple.AppKit              	0x00007fff2eadf829 _DPSNextEvent + 883
9   com.apple.AppKit              	0x00007fff2eade070 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
10  com.apple.AppKit              	0x00007fff2eacfd7e -[NSApplication run] + 658
11  com.apple.AppKit              	0x00007fff2eaa1b86 NSApplicationMain + 777
12  AlexP.SlimHUD                 	0x00000001082cb999 0x1082c8000 + 14745
13  libdyld.dylib                 	0x00007fff6b86fcc9 start + 1

Thread 1:: AMCP Logging Spool
0   libsystem_kernel.dylib        	0x00007fff6b9b0e36 semaphore_wait_trap + 10
1   com.apple.audio.caulk         	0x00007fff65444b16 caulk::mach::semaphore::wait() + 16
2   com.apple.audio.caulk         	0x00007fff654449b2 caulk::semaphore::timed_wait(double) + 106
3   com.apple.audio.caulk         	0x00007fff654447c4 caulk::concurrent::details::worker_thread::run() + 30
4   com.apple.audio.caulk         	0x00007fff654441e4 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 45
5   libsystem_pthread.dylib       	0x00007fff6ba74109 _pthread_start + 148
6   libsystem_pthread.dylib       	0x00007fff6ba6fb8b thread_start + 15

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff6b9b0e36 semaphore_wait_trap + 10
1   com.apple.audio.caulk         	0x00007fff65444b16 caulk::mach::semaphore::wait() + 16
2   com.apple.audio.caulk         	0x00007fff654449b2 caulk::semaphore::timed_wait(double) + 106
3   com.apple.audio.caulk         	0x00007fff654447c4 caulk::concurrent::details::worker_thread::run() + 30
4   com.apple.audio.caulk         	0x00007fff654441e4 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 45
5   libsystem_pthread.dylib       	0x00007fff6ba74109 _pthread_start + 148
6   libsystem_pthread.dylib       	0x00007fff6ba6fb8b thread_start + 15

Thread 3 Crashed:: com.apple.NSEventThread
0   com.apple.CoreFoundation      	0x00007fff3186b0b3 __CFRunLoopServiceMachPort + 549
1   com.apple.CoreFoundation      	0x00007fff31869a52 __CFRunLoopRun + 1319
2   com.apple.CoreFoundation      	0x00007fff31868ece CFRunLoopRunSpecific + 462
3   com.apple.AppKit              	0x00007fff2ec81144 _NSEventThread + 132
4   libsystem_pthread.dylib       	0x00007fff6ba74109 _pthread_start + 148
5   libsystem_pthread.dylib       	0x00007fff6ba6fb8b thread_start + 15

Thread 4:
0   libsystem_pthread.dylib       	0x00007fff6ba6fb68 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	0x00007fff6ba6fb68 start_wqthread + 0

Thread 3 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x000000001000600b  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x000000002b31009c  rsi: 0x000000000000d007  rbp: 0x0000700008baa040  rsp: 0x0000700008ba9fc0
   r8: 0x0000000000000000   r9: 0x00000000ffffffff  r10: 0x0000000000000c00  r11: 0x0000000000000206
  r12: 0x0000700008baa0d0  r13: 0x000000001000600b  r14: 0x0000700008baa120  r15: 0x000000000000d007
  rip: 0x00007fff3186b0b3  rfl: 0x0000000000010202  cr2: 0x000000010c9384e2
  
Logical CPU:     8
Error Code:      0x00000000
Trap Number:     6
</details>

**Comment by AlexPerathoner** [comment]
Unfortunately this is not the only error I have found that makes the app silently crash.
I'm working to solve them

**Comment by AlexPerathoner** [comment]
Apparently these crashes are caused by SlimHUD allocating too many thread ports while getting the display's brightness value... I hope I'll fix this in within the next days

**Comment by AlexPerathoner** [comment]
I think this should do the job, if it crashes again in the next couple days please tell me.
[SlimHUD-v1.3.4.zip](https://github.com/AlexPerathoner/SlimHUD/files/4747489/SlimHUD-v1.3.4.zip)

**Comment by AlexPerathoner** [comment]
Did it crash again?

**Comment by loricheung** [comment]
> Did it crash again?

it works fine. never happen again. Thanks👍

**Comment by arashnrim** [comment]
Hey! For some reason, I've been experiencing this issue as well; at times, it appears that the app quits on itself in the background. This is just a surface-level investigation, though, I'll see if there is anything on my end that causes SlimHUD to display this behaviour.
