### ISSUE TITLE
Volume bar doesn't move from halfway

### ISSUE THREAD

**Issue by ArchDud3** [AlexPerathoner/SlimHUD#144]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [x] Updated SlimHUD to the latest version (if applicable)

### Describe the bug

I recently installed SlimHUD and I noticed the volume bar was always at 50%, no matter what I do. However, the brightness bar still works.

### Steps to reproduce

1. Install SlimHUD
2. Try using the volume

### Expected behavior

The volume should shange

### Environment Information (please complete the following information)

```markdown
- macOS version: Sonoma 14.0
- Mac model: M1 Macbook Air (2020)
- Monitor(s): Prisim+ X300
- Apple Silicon/M1 (yes or no): yes
```

**Comment by ArchDud3** [comment]
Nevermind, it seems to have fixed itself

**Comment by rutgerrrrr** [comment]
This is still happening for me on 1.5.1. Restarting SlimHUD seems to fix it but the bug returns eventually. Happens with the brightness slider as well.

- macOS version: Sonoma 14.2.1
- Mac model: M2 Macbook Pro (2023)
- Monitor(s): MacBook display
- Apple Silicon/M1 (yes or no): yes
