### ISSUE TITLE
Sliders randomly appear on-screen without interaction

### ISSUE THREAD

**Issue by ArashNrIm** [AlexPerathoner/SlimHUD#15]
Hello there!

First off, let me begin by saying my thanks for your work in this project. It indeed has made the UI of the controls much more cool-looking and natural!

I'd like to report this bug, albeit minor (non-fatal in any sense); the sliders seem to appear randomly when I'm doing work, and the values change to random values as well. However, I'm still able to adjust any of the three (screen brightness, keyboard brightness, and volume brightness) options and the slider will obey to that. The following is a quick video of what I mean:

![Screen Recording 2020-07-05 at 6 57 33 PM](https://user-images.githubusercontent.com/47273556/86531294-87ec6100-bef2-11ea-97c1-e7ba16ff80a2.gif)

Do note that in the video above, I wasn't interacting with any of the three controls in any way. I hope this helps, and in the meantime I'll try to find a pattern to this occurence, too! Thanks!

**Comment by ArashNrIm** [comment]
Oh, hmm. I found that this is just the result of the keyboard brightness adapting the keyboard to the surroundings. Sorry for the raise!

**Comment by AlexPerathoner** [comment]
Sorry for the late response.
First let me thank you for the time used to contribute to this project and for your appreciation.
Unfortunately I am already aware of this unwanted behaviour and I haven't found a real solution but there is an option in the settings you can use to make the bar appear less often: in the general tab, the margin value. By default it's set to 4% but you can try to increase it up to 10%. Maybe this helps.
PS: you could disable completely the charged bar but that would be a bit drastic.
