### ISSUE TITLE
Bar position doesn't persist across reboots

### ISSUE THREAD

**Issue by ArashNrIm** [AlexPerathoner/SlimHUD#16]
Hello there!

Thanks for creating this awesome product once again.

I've recently been facing a small issue where the position of my bars doesn't persist where they should be across reboots - including shutdowns and restarts.

As an example, before restarting, I've set the position to 'Bottom', and indeed the app has responded as it should. However, upon restarting, this value defaults back to 'Left' again, and the bar shows up on the left.

If I'm honest, though, I haven't done a lot of work to see what was causing this. I have tried changing the position from 'Left' to 'Bottom' and then clicking 'Restart' beside it; all it does it restart the app itself back to the default 'Left'. Side question, is this ('Restart' button restarting and defaulting the app back to as it was) meant to happen as well?

I hope this issue helps. Thanks!

**Comment by AlexPerathoner** [comment]
The restart button is only used to update the bars with settings, so it shouldn't reset anything at all.
This is definitely not a wanted behaviour so I'll investigate on it.
