### ISSUE TITLE
Add option to vary shadow opacity

### ISSUE THREAD

**Issue by arashnrim** [AlexPerathoner/SlimHUD#17]
Hey there!

Thanks so much for working hard on this once again. Apologies for the sudden blast of issues here and there, but this one is more of a suggestion than a bug report!

I'd like to suggest a feature where the opacity of the shadow cast by the bars can be varied (perhaps by using a slider?); this may allow for greater customisability when modifying the look. I tried to play around in a clone, and I believe it's quite feasible (although I'm still mostly tinkering here and there).

I hope you'll be able to take a look at this and hopefully implement this as a feature! Many thanks for your hard work. 👍

**Comment by AlexPerathoner** [comment]
Hi!
May I ask you what were you imagining? The opacity is already max, so here are some variations:
|  standard	|  radius 2x	|  opacity 0.5x	|  radius 0.66x	|  white (lol)	|
|---	|---	|---	|---	|---	|
|  ![standard](https://user-images.githubusercontent.com/31958579/210699889-6aaaf72f-8ad1-4b2b-873f-066eb22fa45e.png)	|  ![radius-2x](https://user-images.githubusercontent.com/31958579/210699899-ef162488-37cb-40a1-a097-2a72ea218a6e.png)	|  ![opacity-0 5x](https://user-images.githubusercontent.com/31958579/210699907-890c403b-9121-461a-878a-b2ba3d897df8.png)	|  ![radiu-0 66x](https://user-images.githubusercontent.com/31958579/210699944-5f292cc7-b203-4686-bf37-bb449378c5b9.png)	|  ![white](https://user-images.githubusercontent.com/31958579/210699955-72ad78b5-c85b-45ca-a4e7-e2d6f1e3cf55.png)	|

**Comment by arashnrim** [comment]
Hey! It's been a minute (haven't been using macOS for over a year now!) but I'm glad to see that you're still working on this!

Unfortunately I can't exactly recall the train of thought that I had, and the first three pictures you've given look more or less the same to me (my bad!). If I were to have a guess, though, I think I can barely recall wishing shadows could be a little lighter especially as they're prominent on bright backgrounds.

Apologies if my answer isn't as helpful as you need!
