### ISSUE TITLE
HUD IS STILL SHOWING

### ISSUE THREAD

**Issue by fabianchua6** [AlexPerathoner/SlimHUD#19]
My HUD is still showing alongside SlimHUD's bar.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/57614749/87250981-0caf2000-c49b-11ea-8881-e7e629d8c074.png">

**Comment by fabianchua6** [comment]
Using latest version 1.3.6

**Comment by AlexPerathoner** [comment]
Have you followed the instructions for the installation? (e.g. have you modified the OSDUIHelper.plist file?)
