### ISSUE TITLE
Bars don't appear on startup

### ISSUE THREAD

**Issue by arashnrim** [AlexPerathoner/SlimHUD#20]
Hey! Thanks for creating SlimHUD once again.

I'm experiencing a bug where the bars don't appear after the Mac starts up. While the SlimHUD app is present in the menu bar, the actual bars (screen brightness, volume, and keyboard brightness) aren't.

This issue may be caused by other factors if this issue can't be replicated elsewhere. I'm currently running macOS 10.15.6 (Catalina), but this issue seems to persist even before I updated (in macOS 10.15.5). I'll try to investigate this issue on my end as well. Hope this helps!

**Comment by AlexPerathoner** [comment]
Does this **always** happen or just sometimes?

**Comment by 0xNotNeo** [comment]
For me it always happens.

**Comment by AlexPerathoner** [comment]
> For me it always happens.

Ok then please try downloading this version, then open the Console app, start SlimHUD.
A message starting with "screenFrame is..." should appear in the console. Please post here the full message.
[SlimHUD.zip](https://github.com/AlexPerathoner/SlimHUD/files/5132894/SlimHUD.zip)

**Comment by 0xNotNeo** [comment]
Here you go:

<img width="680" alt="Screenshot 2020-08-26 at 23 50 55" src="https://user-images.githubusercontent.com/56200813/91360608-10062d00-e7f7-11ea-8231-7b8d3a371889.png">

**Comment by AlexPerathoner** [comment]
Ok at least I'm now sure that it's placing the bars in the correct position. Maybe the animation is failing... I'll continue investigating

**Comment by 0xNotNeo** [comment]
Good luck, I'm here if any help's needed.

**Comment by AlexPerathoner** [comment]
Is there any update on this? Is it still happening?

**Comment by jadtl** [comment]
It's not an issue on my part on MacBook Air M1, macOS Ventura 13.1. I however don't have my original device (MacBook Pro 16" 2019) to test this.

**Comment by AlexPerathoner** [comment]
Good to hear that! Then I'll close this as non-repro
