### ISSUE TITLE
OSX 10.13.6

### ISSUE THREAD

**Issue by romanmorozov81** [AlexPerathoner/SlimHUD#21]
Hello, any chance to run it on 10.13.6 osx?

**Comment by AlexPerathoner** [comment]
I haven't updated my Mac to that version yet due to my slow connection (im on holiday), in a couple of days I'll do it.

**Comment by romanmorozov81** [comment]
10.13.6 it's older version High Sierra, int's not latest Big Sur as you thought
SlimHUD asks 10.14 Mojave, but I'm on 10.13 High Sierra

**Comment by AlexPerathoner** [comment]
Oh, right. I thought it was the update for 10.15.6. My bad.
I removed support for 10.13 as it doesn't support contentTintColor. This means that you won't be able to change the color of the icons. Not a big deal, I'll soon release an update.

**Comment by romanmorozov81** [comment]
I think it's not so important, it's better than nothing) I'm waiting for update. Thank you!

**Comment by AlexPerathoner** [comment]
Just released a new version with High Sierra support. As I don't have any machine to test it on please tell me if doesn't work.

**Comment by romanmorozov81** [comment]
Just tested on High Sierra 10.13.6 (17G14019). It works perfect, all settings work without bugs. Great job! Thank you!

**Comment by romanmorozov81** [comment]
Just one annoying thing - Brightness bar appears when display regulates brightness automatically.

**Comment by AlexPerathoner** [comment]
Unfortunately this is a known issue which I haven't found a way to solve yet. You can try adjusting the margin-value setting. If you don't own a TouchBar device it can also help to turn off the "Continuously check" option.

**Comment by romanmorozov81** [comment]
Adjusting the margin didn't help, just witched off brightness bar. Thank you a lot for this application!
