### ISSUE TITLE
failed hiding macOS HUD (Big Sur)

### ISSUE THREAD

**Issue by dmndrz** [AlexPerathoner/SlimHUD#22]
Hi!
The app itself seems to work perfectly on Big Sur.
But when I try to hide default macOS HUD in Terminal (after having disabled SIP then reboot) I get this:
```
mount_apfs: volume could not be mounted: Permission denied
mount: / failed with 66
```
Then when I try to delete the text in the plist file, it doesn't save the edit.
Is it me doing it wrong or are there new restrictions with Big Sur?

**Comment by DanielVolz** [comment]
Must be a new security restriction of Big Sur. It doesn't work for me either.

**Comment by AlexPerathoner** [comment]
I can confirm this is a new restriction introduced in Big Sur. There are some workarounds which are (obviously..) more complicated than it was before.
Some people fell in a **booting loop** after trying to make their boot disk writable. I therefore **ABSOLUTELY DO NOT RECOMMEND** trying this on your main disk. I haven't tried it out yet.

[Here](https://twitter.com/EBADTWEET/status/1275454103900971012?s=20)'s the instructions I found.
