### ISSUE TITLE
Thoughts on Big Sur workaround

### ISSUE THREAD

**Issue by 3raxton** [AlexPerathoner/SlimHUD#24]
Great work on SlimHUD. I absolutely love it and appreciate the hard work you've put into it. It's unfortunate that Apple has changed its security approach, causing the issues you're currently dealing with. That being said, I've been thinking a bit about workarounds and thought I'd share an idea I had. 

When installing MacForge on my Mac on Big Sur, I looked at how the plugins were injected into the OS. Could it be possible to do something along those lines with SlimHUD to override the current brightness, volume, and other HUDs? I'm not sure how relevant this is to a solution but figured it couldn't hurt to share.

 Thanks again for all your hard work, looking forward to updates!

**Comment by AlexPerathoner** [comment]
I haven't heard about MacForge, sound like a cool app! I'll check it soon and look what I can do with SlimHUD...

**Comment by 3raxton** [comment]
Here's the link to it to save you some time: https://github.com/MacEnhance/MacForge

Also, please, take your time on the workaround. I'm happy to wait as I'm sure it's been more of a challenge than expected to find a workaround for Big Sur. Again, great work!

**Comment by 3raxton** [comment]
First and foremost, I want to be clear that I am not affiliated with the creators of MacForge (I am listed as a contributor on the repo; all I did was change a link in the README) and don't want to make you feel imposed to port to MacForge as an alternative but figured I'd share this since it could be a quick and easy workaround for people who want to use SlimHUD on macOS 11+. 

——————

I've been thinking more about this and figured I'd follow up. I took a deeper look into MacForge and the requirements for injecting apps as bundles using MacForge. They all rely on Xcode, and it seems like you could port your code from SlimHUD to a MacForge plugin / bundle to keep it working for the time being on macOS 11+. 

Unfortunately, I know this would mean that, for the time being, SlimHUD wouldn't be a standalone app. However, it could be the perfect alternative to provide SlimHUD to users willing to try this approach. If you're interested in this as a potential and easier workaround, you can take a look at how bundles work on MacForge. 

https://github.com/MacEnhance/MacForge#developer-
https://github.com/MacEnhance/MacForge/wiki/Bundles-:-Creating

Hopefully this helps a bit!

**Comment by AlexPerathoner** [comment]
Even if you were affiliated with MacForge it wouldn't be a problem. In fact, everyone is trying to "feather one's own nest". 
However, I'm currently really not having time to do it. I confess that I just took a look at MacForge, and didn't start working on it. But I can't imagine this being a quick work.
In this months I'm just having too much to do. I'll implement off and on some new features in this or other of my projects, but nothing exceptional. 

Sorry about it, but it will probably take several months before SlimHUD appears on MacForge.

**Comment by 3raxton** [comment]
No worries, I don't want to make you feel rushed; I just wanted to share an alternative approach for a workaround for BigSur. I understand how long projects can take and the amount of work that goes into them, so please, take all the time you need. 

I'll be on the lookout for updates in the meantime! Be well, be safe, and thanks for all your hard work on SlimHUD; it really improved my experience on my Mac! Apprecaite it.
