### ISSUE TITLE
Brightness bar stuck at 100%

### ISSUE THREAD

**Issue by kaydenanderson** [AlexPerathoner/SlimHUD#29]
Hey! Just tried out the app and love the way it looks and feels - my only reservation is that the screen brightness bar is always stuck at 100%. It doesn't move, no matter where I put it on screen or set my brightness to.
Is there a fix for that that I am not aware of?
Thanks in advance for any help!

**Comment by AlexPerathoner** [comment]
Hi kaydenanderson!
Thanks for the appreciation. Unfortunately this seems to be a frequent issue, to which I haven't found a solution yet. These months I'm quite busy with work and exam so I probably won't be able to take a deeper look...
Feel free to open a PR if you find a solution!
