### ISSUE TITLE
Bars are shown by automatic brightness correction

### ISSUE THREAD

**Issue by linesplitter91** [AlexPerathoner/SlimHUD#3]
To see the Bars by changing the Brightness manually is a good thing. But the Mac change the Display and Keyboard Brightness by itself. In this Situation the Bar is very disruptive at working on Mac. An option to disable the Bar by automatic changes would improve the Functionality.

**Comment by AlexPerathoner** [comment]
Unfortunately I haven't found a way to filter user and non-user actions yet. But I know that it is annoying, will try to fix it

**Comment by AlexPerathoner** [comment]
So I found a way to partially prevent this: instead of continuously checking for any changes in the brightness I'm checking if the change's amount was greater than a given value. This doesn't completely solve the issue, but makes it more rare.
However it also increases the CPU usage (energy usage is still zero) - Would you be fine with this kind of solution?

**Comment by linesplitter91** [comment]
Its your Project, but I think its a good solution :)

**Comment by AlexPerathoner** [comment]
With the latest update I've implemented what I suggested in my last comment. Is it better now?

**Comment by linesplitter91** [comment]
The Position ist fine but I think that's another thread right? XD

**Comment by AlexPerathoner** [comment]
My bad, should have committed twice. In the last update I fixed that other thread, but also added a function that shows the bar only when its value changes more than 5%. Let me know if the bar still appears too often, I could try increasing the percentage or making it settable...

**Comment by linesplitter91** [comment]
I think it is better to implement a setting for this. Otherwise you can integrate checkboxes for every Bar Type, than users can disable single bars.

**Comment by AlexPerathoner** [comment]
I just released a new version.
I've implemented the setting we talked about, and also added a setting to toggle each bar.

**Comment by linesplitter91** [comment]
mega nice :)
