### ISSUE TITLE
Suspend OSDUIHelper instead of disabling launch agent?

### ISSUE THREAD

**Issue by GameParrot** [AlexPerathoner/SlimHUD#30]
It is possible to stop the system volume/brightness overlays by suspending OSDUIHelper. This could allow you to use the app without disabling SIP. To suspend the process in Swift, you could use 
```
let task = Process()
task.executableURL = URL(fileURLWithPath: "/usr/bin/killall")
task.arguments = ["-STOP", "OSDUIHelper"]
try? task.run()
```
at the beginning of `applicationDidFinishLaunching`.

**Comment by AlexPerathoner** [comment]
Oh, interesting. Does this work on newer versions of macOS, too?

**Comment by GameParrot** [comment]
Works on Monterey

**Comment by AlexPerathoner** [comment]
Cool, that could actually be a great way to solve it. I'll look into it next month, after exam-phase 😢

**Comment by AlexPerathoner** [comment]
Forgot about it, working on it these days. Will release an update before Thursday

**Comment by AlexPerathoner** [comment]
I've created a [new branch](https://github.com/AlexPerathoner/SlimHUD/tree/develop/osduielper-stop). Could @AjayShanker-geek or @GameParrot please run it and confirm me if it's working newer versions?

**Comment by AjayShanker-geek** [comment]
Need sometime as currently my SIP is disabled because of `yabai`
