### ISSUE TITLE
arm64 Build

### ISSUE THREAD

**Issue by AjayShanker-geek** [AlexPerathoner/SlimHUD#38]
I manage to build it by disabling `lastCheckForUpdatesOutlet` due deprecated sparkle package.

<img width="1728" alt="Screenshot 2022-12-19 at 11 53 43 PM" src="https://user-images.githubusercontent.com/26241915/208466873-987d5cd2-831b-40f0-92af-fa864bca075b.png">

Sorry, I have never used sparkle to help you to port over😅

**Comment by AlexPerathoner** [comment]
I think there are multiple problems when building with recent versions of MacOS (probably this [GitHub Action](https://github.com/AlexPerathoner/SlimHUD/actions/runs/3730267382) is failing for that reason, too). This evening I'll install Ventura and try to fix at least some of them.

If I'm not mistaken there should be a newer version of Sparkle.

**Comment by AlexPerathoner** [comment]
Does it still not compile?

**Comment by AjayShanker-geek** [comment]
Closing, as Sparkle has been update and I manage to compile it successfully. Thanks @AlexPerathoner
