### ISSUE TITLE
'Launch at login' may still be broken

### ISSUE THREAD

**Issue by dmndrz** [AlexPerathoner/SlimHUD#6]
Hi!
I updated to the 1.1.1 version but it seems that the 'launch at login' option isn't fixed (or is there something else to do than just replace with the new app file?)

**Comment by AlexPerathoner** [comment]
Working on that.
It should be possible to update simply by replacing the file, so you have not done anything wrong.

**Comment by AlexPerathoner** [comment]
Maybe closing this issue was a bit pre-mature...
I've just uploaded a new [version](https://github.com/AlexPerathoner/SlimHUD/releases/tag/v1.1.3) which should finally fix this.
At the moment it's a pre-release but as soon as you confirm me that it works I will edit it and mark it as an appropriate release.

**Comment by dmndrz** [comment]
Nope 🙁
Still doesn't work for me. Even after a clean install.
I can fix this by manually add the app in the system preferences > users and groups > login items tab, but it won't fix it properly within the app itself.

**Comment by AlexPerathoner** [comment]
Unfortunately that doesn't count as a fix 😂
If you open `/Applications/SlimHUD.app/Contents/MacOS/SlimHUD` do you get any error print in the terminal window when toggling the launch at login check-box?

**Comment by dmndrz** [comment]
Nothing happens in the terminal window when I do this.

**Comment by AlexPerathoner** [comment]
And if you enable it and then relaunch the app (without restarting your pc) is the checkbox still on?

**Comment by dmndrz** [comment]
No it’s not. Each time I enable it, relaunch the app, and it’s off again. It’s weird because all other settings stay in place, except this one.

**Comment by AlexPerathoner** [comment]
It seems like the library that should do that is not working properly. But it’s strange that it’s not returning any error. Tomorrow I’ll continue investigating...
Il 13 apr 2020, 22:55 +0200, Damien <notifications@github.com>, ha scritto:

**Comment by AlexPerathoner** [comment]
Here's the latest version. I really hope this works... Please let me know if not.
[SlimHUD-Cyanocitta-v1.1.4.dmg.zip](https://github.com/AlexPerathoner/SlimHUD/files/4476657/SlimHUD-Cyanocitta-v1.1.4.dmg.zip)

**Comment by dmndrz** [comment]
I'm happy to say that it's fixed! ☺️

The only thing is (sorry haha) I was unable to open the app in a proper way, even with SIP disabled I had to chose between cancel or delete the file:
<img width="532" alt="Capture d’écran 2020-04-14 à 20 46 53" src="https://user-images.githubusercontent.com/18632343/79263535-47e98500-7e93-11ea-8f07-dd0fd3d70ea4.png">
To force launch, I had to use this command in Terminal: `xattr -rc` and drag the app.
I don't know if it's because you put the file in this conversation or not.

(By the way, where can I suggest new features? If you accept suggestions, of course)

**Comment by AlexPerathoner** [comment]
I'll be working on that, too.
Btw I don't know if you have disabled SIP to try opening the app but if so know that it should never be necessary. After changing the OSDUIHelper.plist file you can re-enable SIP and keep it enabled.

Any suggestion is highly welcome! You can just open an issue for that and assign its label.

**Comment by dmndrz** [comment]
Yes, I should have disabled GateKeeper instead of SIP, I mixed the two.

**Comment by AlexPerathoner** [comment]
Ok, I think I have finally (and I know that this is becoming repetitive 😅) got it.

[SlimHUD-Cyanocitta-v1.1.4.dmg.zip](https://github.com/AlexPerathoner/SlimHUD/files/4483045/SlimHUD-Cyanocitta-v1.1.4.dmg.zip)

**Comment by dmndrz** [comment]
Everything works! Great job! 😉
