### ISSUE TITLE
Recreate Icon

### ISSUE THREAD

**Issue by AlexPerathoner** [AlexPerathoner/SlimHUD#70]
- too big

![Screenshot 2023-01-04 alle 22 26 14](https://user-images.githubusercontent.com/31958579/210652971-84e9e5fe-b121-4033-b126-c95314610ecf.png)

**Comment by kaydenanderson** [comment]
do you have any attachment to the bird design? i’d love to create an icon for you!

**Comment by AlexPerathoner** [comment]
That would be really cool!
I'm not really attached to it. The bird comes from the original name of the app, but now it doesn't make sense. And even though I like the way it looks in the menu bar, a change would be good.

btw: ignore the reaction to the comments, they are from a kinda-broken automatic workflow which I'll fix these next days

**Comment by kaydenanderson** [comment]
hey! i've got a quick first draft here:
![Icon-MacOS-512x512@1x](https://user-images.githubusercontent.com/104660117/210714916-d42a07f6-2fdd-49e2-96f7-2e305492f8d0.png)
what would you like me to change?
(or start over, in case you don't like it)
i'm more than happy to change anything at all :)

**Comment by kaydenanderson** [comment]
@AlexPerathoner hey! sorry for the super late work. here's a rethought design - early stages, of course - that's kind of representative of the size difference and purpose of your app. it looks a little barren, and im super open to hearing any ideas on what else to include. anyways, here's how it looks right now:
![9Icon-MacOS-512x512@2x](https://user-images.githubusercontent.com/104660117/211717844-3c0ccdf3-94fc-444a-b54c-127bb44924b3.png)
do you want me to add/remove/change/start over? i'm super open to ideas :)
let me know!

**Comment by AlexPerathoner** [comment]
This also looks great! What was the thought process behind the mouse pointer?
btw I think this shape should work well in the menu bar, too 💯

**Comment by kaydenanderson** [comment]
i was thinking that the cursor would help demonstrate the size of the hud - especially since the native macOS hud is known to be *massive*, and your app is called “slimhud”.

is there anything else that you want put into it? objects, colors, etc. 

also, what kind of menu bar icon are you envisioning?

**Comment by AlexPerathoner** [comment]
What about this?
<img src="https://user-images.githubusercontent.com/31958579/211914603-9c8e0692-2815-44d8-90e9-bfcaa7b4a515.png" width=200>
I think that, thanks to the large amount of white, it still gives a feeling of "slimness". If you're happy with this change I'd ask a couple of people which one of the [two](https://user-images.githubusercontent.com/104660117/210714916-d42a07f6-2fdd-49e2-96f7-2e305492f8d0.png) they prefer, and add the winner in the next release

For the menu bar I was thinking about something similar:
![status-scaled-32](https://user-images.githubusercontent.com/31958579/211914850-bde469fb-a251-4ca7-8595-b1500a3b71a0.png)
But if it's so small it doesn't look good, in fact it gives a "chunky" feeling, opposite to its bigger version.
I also tried the first menu bar icon of last week, but I think it looked a bit anonymous:
![image](https://user-images.githubusercontent.com/31958579/211915098-b81cc5b5-d6d2-4116-a4bd-37d186696af9.png)

**Comment by kaydenanderson** [comment]
awesome! are you liking the anonymous look or do you want me to draft up a new menu bar icon consistent with the icon? or something new?
it’s not my icon - so my opinion isn’t as significant as yours. but i do think that it does look better without the cursor, actually :)
let me know!

**Comment by AlexPerathoner** [comment]
If you could create a draft for the menu bar it would be really cool - but I don't think it needs to be consistent with the icon.
I'd prefer it to be recognisable and nice looking. We can also keep the bird, the one up there is pretty nice :3 



<br><br><br><br>


![image](https://user-images.githubusercontent.com/31958579/211953407-2e7568bf-2017-4137-b0b9-5de41856a93e.png)

**Comment by kaydenanderson** [comment]
sounds good! i was worried i couldn’t measure up to the bird 😆
i’ll get on refinements for the final design.

**Comment by kaydenanderson** [comment]
heyo! i just finished a copy of the main app icon. still workshopping the menubar icon - though chunky, i think the square icon deserves a chance haha
let me know what you think!
![9Icon-MacOS-512x512@2x](https://user-images.githubusercontent.com/104660117/212242912-bb1e601d-27f6-4479-ad9d-c1ce3db5c9a7.png)

**Comment by AlexPerathoner** [comment]
I've created a [google form](https://forms.gle/wtc7w3GN3VSe4TyC9) with all the icons (except for the one with the mouse, sorry ahah). Send it to some people and in a couple of days we'll decide on which to use

**Comment by AlexPerathoner** [comment]
Regarding the icon they were overall all really close (except the bird xD)
However,
1 was by far the one that won "slim, clean" and, together with 2 was the most liked one.
3 was the most recognisable, followed by 2, 6
5 by far the most "macOS" one

<img src="https://user-images.githubusercontent.com/31958579/212568563-a5099da9-0a48-4ecb-ba63-f777dee1a328.png" width=200>


So I would go for something between 1 and 2

Could you please also send me the file for the first icon? I guess that was done with Sketch too, right? I'd like to try adding some shadows as that's probably what gives the "macOS" look to the 5

**Comment by prcmelo** [comment]
Maybe I'm too late for the party, but following the beautiful idea from @kaydenanderson I would like to share my icon idea
![CleanShot 2023-01-21 at 1 13 00](https://user-images.githubusercontent.com/123224781/213843146-98970ef5-2ccc-439a-b886-f67c4b522144.png)

Also, I'd like to say that I've always been a huge fan of this project, and if I'm allowed, I'd like to make two suggestions...

1 - An option to hide the icon from the menu bar

2 - Eliminate the shadow that overlaps the background when we change the volume, or brightness

This project is wonderful, no matter what, keep going please ;-)

**Comment by AlexPerathoner** [comment]
Hi @prcmelo , thanks for the icon, the shadows effect is something we will definitely use in the final design. Regarding your suggestions: for 1 there's these issues: #105 #106 ; while 2 is already in the settings, under the "Style" tab, "Shadows" checkbox

**Comment by prcmelo** [comment]
@AlexPerathoner thanks for the answer. I think I didn't explain it well when I talk about shadows. See the attached image, the shadow of the "current volume" (01), is overlapping the background of the "total volume", (02), thus creating a very dark shadow due to the fact that there are two shadows, (from 01 and 02), one on top of the other. See if the image makes it clearer what I'm trying to say, please. Oh yes, sorry, I didn't know if I needed to open a new thread for this, so if needed, you can move this thread to a new one, please. Thanks again, and greetings from Rio de Janeiro, Brazil.
![CleanShot 2023-01-21 at 4 39 21](https://user-images.githubusercontent.com/123224781/213884803-879c72a2-1d1c-4972-ab33-76b209bc88c9.png)

**Comment by AlexPerathoner** [comment]
<img src="https://user-images.githubusercontent.com/31958579/213894324-58853f73-ae81-4e31-a0f9-76933b7a32c4.png" width=300><img src="https://user-images.githubusercontent.com/31958579/213894327-ff17b6b8-85d9-4f2a-9b7c-1e9968dc5ab9.png" width=300><img src="https://user-images.githubusercontent.com/31958579/213894330-a5091312-3bfb-412a-a60c-6f1ffefb865b.png" width=300><img src="https://user-images.githubusercontent.com/31958579/213894331-d23dcaef-9ec6-4ff4-bfb6-76575c8ffa1d.png" width=300>

Which is best @kaydenanderson ?

**Comment by kaydenanderson** [comment]
hey @AlexPerathoner! i'm so sorry - i didn't get an email about this comment (at least, i don't think!)
i prefer 1. it looks the most macOS-like. sorry about my inactivity! it's midterms flagging week ahaha
slightly off topic of this specific issue but i also downloaded and built the latest push for your settings redesign. it looks great! i'm not sure what's happening in the dark > light transition; do you think it could be a storyboard issue? are there specific storyboards that can be used with dark and light appearances?

**Comment by AlexPerathoner** [comment]
Hi, fortunately the 1. is the one I chose ahah (with a bit different colors, tho)

No idea on the dark / light transition. In fact, it should be handled by the OS
