### ISSUE TITLE
Icons color can't be changed

### ISSUE THREAD

**Issue by Dybo007** [AlexPerathoner/SlimHUD#80]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Updated SlimHUD to the latest version (if applicable)

### Describe the bug

It stay white with, it seems, an opacity reduced...
macOS 12.5 MacBookAir M2
<img width="633" alt="Screenshot at Jan 07 15-41-10" src="https://user-images.githubusercontent.com/122163707/211156282-14120ca3-15c2-40b6-9761-11bc53f8d9c9.png">
<img width="58" alt="Capture d’écran 2023-01-07 à 15 41 26" src="https://user-images.githubusercontent.com/122163707/211156283-779b9cd0-ec11-4b7d-b2d8-fabd41e92db2.png">

### Steps to reproduce

Settings Style Icons 

### Expected behavior

The color have to be changed

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.5
- Mac model: macbook air
- Monitor(s): integrated
- Apple Silicon/M2 (yes or no): Yes
```

**Comment by AlexPerathoner** [comment]
Hi Dybo, thanks for taking your time and reporting this! This issue should have already been fixed. I'll release a new version with the fix these next days

**Comment by Dybo007** [comment]
Thank you for taking time for this!! I'll wait. Even if it's not 
Thanks for your app too!!! 👍🏼

**Comment by AlexPerathoner** [comment]
Should also be fixed

**Comment by Dybo007** [comment]
Perfect!! You're a BOSS!! Thank you soooo much!! 👍🏼
