### ISSUE TITLE
Bar can't be resized

### ISSUE THREAD

**Issue by Dybo007** [AlexPerathoner/SlimHUD#81]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Updated SlimHUD to the latest version (if applicable)

### Describe the bug

It's just displaced!! 
Over 200, all's fine, but if i set the size too low, the icons and bars disappear partialy as far as i decrease.
PS excuse my poor english, french here.

<img width="351" alt="Capture d’écran 2023-01-07 à 15 48 30" src="https://user-images.githubusercontent.com/122163707/211156631-86f019b0-fbcb-42c6-a9f4-e5af7f706810.png">
<img width="51" alt="Capture d’écran 2023-01-07 à 15 50 37" src="https://user-images.githubusercontent.com/122163707/211156638-b3ee91c4-deef-416c-8122-c4e313ffe6fa.png">

### Steps to reproduce

settings position size

### Expected behavior

It should be visible completely

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.5
- Mac model: Macbook Air
- Monitor(s): internal
- Apple Silicon/M2 (yes or no): Yes
```

**Comment by AlexPerathoner** [comment]
Hi Dybo, thanks for taking your time and reporting this! In the coming release this should be fixed, too

**Comment by Dybo007** [comment]
Ok i wait for these fixes. Many thanks for your work again!!

**Comment by AlexPerathoner** [comment]
Should now be fixed
