### ISSUE TITLE
Feature request : style for icons

### ISSUE THREAD

**Issue by dmndrz** [AlexPerathoner/SlimHUD#9]
I think it would be a great addition to be able to change icons color and/or opacity, as we can do for the bars. According to the wallpaper (specifically with the Catalina one throughout the day), sometimes the icon becomes invisible. And it would be even better if it changed automatically with light and dark modes.

**Comment by AlexPerathoner** [comment]
Will do it!

**Comment by AlexPerathoner** [comment]
![Schermata 2020-04-20 alle 20 52 47](https://user-images.githubusercontent.com/31958579/79788424-eb7dde00-8348-11ea-9ef0-19caee8387e7.png)
I'm working on how to present the settings and I'm afraid that the layout in the screen could be a bit confusing. What do you think?

**Comment by dmndrz** [comment]
I see what you mean. Maybe you can separate the two columns (bars and icons) in two tabs so they’re not both visible at the same time ?

**Comment by dmndrz** [comment]
Maybe you can have something like this?
<img width="710" alt="Cyanocitta UI" src="https://user-images.githubusercontent.com/18632343/79898926-52180000-840c-11ea-9103-14e82fd2d0ff.png">

**Comment by AlexPerathoner** [comment]
Looks good!
Il 21 apr 2020, 20:12 +0200, Damien <notifications@github.com>, ha scritto:

**Comment by AlexPerathoner** [comment]
![Registrazione schermo 2020-04-26 alle 17 04 47](https://user-images.githubusercontent.com/31958579/80311544-8579d680-87e0-11ea-8322-d76eb0eeb2a4.gif)
Like this should be fine, right?

**Comment by dmndrz** [comment]
Yes, that's great!

**Comment by AlexPerathoner** [comment]
I have just drafted a [pre-release](https://github.com/AlexPerathoner/SlimHUD/releases/tag/v1.2.0) with this feature. I'll wait you to prove me that everything works as it should and then I'll modify it as a proper release.

**Comment by dmndrz** [comment]
Everything works perfectly well!
